config/routes.rb
Rails.application.routes.draw do
  
  resources :events 
  
  get '/events/:id/subscribe', to: 'events#subscribe', as: 'subscribe_event'

  devise_for :users
  root 'home#index'
  

# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord

	belongs_to :creator, class_name: "User"
	has_many :event_attendees 
	has_many :attendees, through: :event_attendees
end

app/models/event_attendee.rb
class EventAttendee < ApplicationRecord
	belongs_to :event 
	belongs_to :attendee, class_name: 'User', foreign_key: :attendee_id
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  has_many :created_events, class_name: "Event", foreign_key: :creator_id 
  has_many :event_attendees, foreign_key: "attendee_id"
  has_many :attending_events, through: :event_attendees, source: :event 

  attr_accessor :login 
  
  validates :username, presence: true, uniqueness: {case_sensitive: false}, format: {with: /\A[a-zA-Z0-9 _]*\z/} 

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  def self.find_first_by_auth_conditions(warden_conditions)

  	conditions = warden_conditions.dup

    if login = conditions.delete(:login)

      where(conditions.to_hash).where("lower(username) = :value OR lower(email) = :value", value: login.downcase).first

    else

      where(conditions.to_hash).first

  end
end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	

	before_action :configure_devise_parameters, if: :devise_controller?

	def configure_devise_parameters

		devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:username, :email, :password, :password_confirmation )}
	
	end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController


  def new

  	@event = Event.new 

  end

  def create

  
  	@event = Event.new(params_permit)
  	@event.creator_id = current_user.id
    @event.save

    redirect_to event_path(@event.id)

  end

  def params_permit

  	params.require(:event).permit(:title, :descr, :date, :place)

  end

  def show

    @event = Event.find(params[:id])
    
  end

  def index

    @event = Event.all
    
  end

  def subscribe

    @event = Event.find(params[:id])
    
        @event.attendees << current_user

   redirect_to event_path(@event.id)


  end


end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def private
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper


end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/create.html.erb
<h1>Event#create</h1>
<p>Find me in app/views/event/create.html.erb</p>

app/views/events/index.html.erb
<h1>Evenements à venir</h1>

	<% @event.each do |e| %>
		<% if e.date >= Date.today %>

			<p>Nom : 
				<%= e.title %>
			</p>
			<p>
				Description :
				<%= e.descr %>
			</p>
			<p>
				Ou ?
				<%= e.place %>
			</p>
			<p>
				Date :
				<%= e.date %>
			</p>
			<a href="<%= event_path(e.id) %>" class="btn btn-lg btn-info" >Voir l'evenement</a>
			<a href="<%= subscribe_event_path(e.id) %>" class="btn btn-lg btn-success">S'inscrire à l'evenement</a>
		<% end %>

	<% end %>

<h1>Evenements passés</h1>

	<% @event.each do |e| %>
			<% if e.date < Date.today %>

				<p>Nom : 
					<%= e.title %>
				</p>
				<p>
					Description :
					<%= e.descr %>
				</p>
				<p>
					Ou ?
					<%= e.place %>
				</p>
				<p>
					Date :
					<%= e.date %>
				</p>
			<a href="<%= event_path(e.id) %>" class="btn btn-lg btn-info" >Voir l'evenement</a>
			<a href="#" class="btn btn-lg btn-success disabled">S'inscrire à l'evenement</a>		
			<% end %>

	<% end %>

app/views/events/new.html.erb
<h1>Crée un evenement</h1>

<%= form_for @event, url: events_path do |f| %>

 	<div class="field">
    <%= f.label :Nom %><br/>
    <%= f.text_field :title, autofocus: true, autocomplete: "titre" %>
 	 </div>

     <div class="field">
    <%= f.label :Quoi? %><br />
    <%= f.text_area :descr, size: "60x12" %>
  	</div>

   <div class="field">
    <%= f.label :Ou? %><br />
    <%= f.text_field :place, autocomplete: "Où se passe l'evenement" %>
 	 </div>

  	<div class="field">
    <%= f.label :Quand? %><br />
    <%= f.datetime_field :date %>
 	</div>

 	 <div class="actions">
    <%= f.submit "Créer" %>
  	</div>


<% end %>

<%= debug current_user.id %>

app/views/events/show.html.erb
<div class="container">

	<h1 class="row"><%= @event.title %></h1>

	<p>Le <%= @event.date %></p>
	<p>A <%= @event.place %></p>
	<p>Description <%= @event.descr %></p>

	<h1 class="row">Listes des invités</h1>


  <% @event.attendees.each do |att| %>
  <p><%= att.username %></p>
<% end %>



	
</div>

app/views/home/index.html.erb
<div class="container">

	<h1 class="title">Eventbrite</h1>
	<p class="text_front_page">le partenaire de tous tes évènements</p>

</div>

app/views/home/private.html.erb
<h1>Home#private</h1>
<p>Find me in app/views/home/private.html.erb</p>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">EventBrite</a>
    </div>
    <ul class="nav navbar-nav">
      <li><a href="/">Accueil</a></li>
      <li><%= link_to 'Evenements', events_path %></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
            <li><%= link_to'Mon compte', edit_user_registration_path %></li>
            <li><%= link_to 'Créer un evenement', new_event_path %></li>
            <li><%= link_to 'Se deconnecter', destroy_user_session_path, method: :delete %></li>
        <% else %>
            <li><%= link_to 'Se connecter', new_user_session_path %></li>
        <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Eventbrite</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
      <!-- CDN Bootstrap -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <!-- FontAwesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.12/css/all.css" integrity="sha384-G0fIWCsCzJIMAVNQPfjH08cyYaUtMwjJwqiRKxxE/rx96Uroj1BtIQ6MLJuheaO9" crossorigin="anonymous">
    <!-- Font personalisée -->
    <link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet">
  </head>

  <body>

       <%= render 'layouts/header' %>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>

  



  </body>
</html>